### ISSUE TITLE
Help with custom mapping -- missing header keyword: delimiter not working?

### ISSUE THREAD

**Issue by sphakka** [reubano/csv2ofx#26]
I'm trying to convert CVS reports from UBS Switzerland, which come (in French, UTF-8 encoding) like this:
```
Produit;Monn.;Description;Date de valeur;Description 1;Description 2;Description 3;N° de transaction;Débit;Crédit;Solde
0123 45678900.01C;CHF;Compte personnel UBS;07.11.2017;Ordre e-banking;Payeur 1;Votre facture #123;123456789;334.9;;1000
0123 45678900.01C;CHF;Compte personnel UBS;06.11.2017;Virement postal;Payeur 2;Remboursement;9876543210;;72;737.1  
```

Starting from the shipped "ubs" mapping, I wrote the following new one (minimal, not complete):
```
from __future__ import absolute_import
from operator import itemgetter
mapping = {
    'delimiter' : ';',
    'has_header': True, # apparently mandatory...
    'currency'  : itemgetter('Monn.'),
    'account'   : itemgetter('Produit'),
    'amount'    : lambda tr: tr.get('Débit', tr['Crédit']),
    'date'      : itemgetter('Date de valeur'),
}

```
However (working in a virtualenv based on Python-3.4.6) it doesn't seem to work:
```
$ csv2ofx -m ubs_ch-fr UBS-CH_export_test.csv 
Field 'Produit' is missing from file. Check `mapping` option.
``` 
...with the following stack trace:
```
Traceback (most recent call last):
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/meza/fntools.py", line 629, in byte
    bytes_ = content.encode(ENCODING)
AttributeError: 'itertools.islice' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/csv2ofx/main.py", line 183, in run
    res = write(dest, IterStringIO(content), **kwargs)
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/meza/io.py", line 1323, in write
    return sum(read_any(filepath, writer, mode, content, **kwargs))
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/meza/io.py", line 445, in read_any
    for line in _read_any(filepath, reader, args, **kwargs):
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/meza/io.py", line 371, in _read_any
    for num, line in enumerate(reader(f, *args, **kwargs)):
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/meza/io.py", line 1301, in writer
    for chunk in ft.chunk(content, chunksize):
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/meza/fntools.py", line 665, in <genexpr>
    generator = (content.read(chunksize) for _ in it.count())
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/meza/io.py", line 138, in read
    return self._read(self.iter, num, False)
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/meza/io.py", line 122, in _read
    byte = ft.byte(content)
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/meza/fntools.py", line 634, in byte
    bytes_ = b''.join(map(encode, content))
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/meza/io.py", line 65, in <genexpr>
    encode = lambda iterable: (s.encode(ENCODING) for s in iterable)
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/csv2ofx/ofx.py", line 439, in gen_body
    for datum in data:
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/csv2ofx/utils.py", line 152, in gen_data
    for group, main_pos, sorted_trxns in groups:
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/csv2ofx/__init__.py", line 294, in clean_trxns
    for grp, trxns in groups:
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/csv2ofx/__init__.py", line 280, in gen_trxns
    for grp, transactions in groups:
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/csv2ofx/ofx.py", line 479, in gen_groups
    for gee in group(cleansed, keyfunc):
  File "/home/marcoep/projects/python/_venvs/env1/lib/python3.4/site-packages/meza/process.py", line 588, in group
    sorted_records = sorted(records, key=keyfunc)
KeyError: 'Produit'
``` 
What's interesting is that the `records` list (at `meza/process.py:588`) looks like
```
[{'Produit;Monn.;Description;Date de valeur;Description 1;Description 2;Description 3;N° de                
transaction;Débit;Crédit;Solde': '0123 45678900.01C;CHF;Compte personnel UBS;07.11.2017;Ordre              
e-banking;Payeur 1;Votre facture #123;123456789;334.9;;1000'}, {'Produit;Monn.;Description;Date de         
valeur;Description 1;Description 2;Description 3;N° de transaction;Débit;Crédit;Solde': '0123              
45678900.01C;CHF;Compte personnel UBS;06.11.2017;Virement postal;Payeur                                    
2;Remboursement;9876543210;;72;737.1'}]
```
...as if the delimiter were not taken into account. Any idea?

**Comment by nicdumz** [comment]
+1

Debugging further, the problem is that read_csv is not taking into account delimiters at all. It assumes `,` is the delimiter. (I'm not sure why the author uses meza for csv parsing, when the csv module works pretty well for me)

Anyways, I then modified the example to get rid of meza libraries which seem to break for me. Ended up with:

```python
from __future__ import absolute_import, print_function

import csv
import itertools as it

from csv2ofx import utils
from csv2ofx.ofx import OFX
from csv2ofx.mappings.ubs import mapping

ofx = OFX(mapping)
with open('/home/youruser/Downloads/export.csv', 'rb') as f:
    reader = csv.DictReader(f, delimiter=';')
    groups = ofx.gen_groups(reader)
    trxns = ofx.gen_trxns(groups)
    cleaned_trxns = ofx.clean_trxns(trxns)
    data = utils.gen_data(cleaned_trxns)
    print(ofx.header())
    for b in ofx.gen_body(data):
        print(b)
    print(ofx.footer())
    for c in content:
        print(c)
```

But I still have encoding errors:

```
Traceback (most recent call last):
  File "myfile.py", line 18, in <module>
    for b in ofx.gen_body(data):
  File "/home/someuser/code/ubs2ofx/venv/local/lib/python2.7/site-packages/csv2ofx/ofx.py", line 439, in gen_body
    for datum in data:
  File "/home/someuser/code/ubs2ofx/venv/local/lib/python2.7/site-packages/csv2ofx/utils.py", line 152, in gen_data
    for group, main_pos, sorted_trxns in groups:
  File "/home/someuser/code/ubs2ofx/venv/local/lib/python2.7/site-packages/csv2ofx/__init__.py", line 296, in clean_trxns
    for grp, trxns in groups:
  File "/home/someuser/code/ubs2ofx/venv/local/lib/python2.7/site-packages/csv2ofx/__init__.py", line 282, in gen_trxns
    for grp, transactions in groups:
  File "/home/someuser/code/ubs2ofx/venv/local/lib/python2.7/site-packages/csv2ofx/ofx.py", line 476, in gen_groups
    {k: next(xmlize([v])) for k, v in c.items()} for c in chnk]
  File "/home/someuser/code/ubs2ofx/venv/local/lib/python2.7/site-packages/csv2ofx/ofx.py", line 476, in <dictcomp>
    {k: next(xmlize([v])) for k, v in c.items()} for c in chnk]
  File "/home/someuser/code/ubs2ofx/venv/local/lib/python2.7/site-packages/future/builtins/newnext.py", line 59, in newnext
    return iterator.next()
  File "/home/someuser/code/ubs2ofx/venv/local/lib/python2.7/site-packages/meza/fntools.py", line 740, in xmlize
    yield mreplace(item, replacements)
  File "/home/someuser/code/ubs2ofx/venv/local/lib/python2.7/site-packages/meza/fntools.py", line 365, in mreplace
    return reduce(func, replacements, content)
  File "/home/someuser/code/ubs2ofx/venv/local/lib/python2.7/site-packages/meza/fntools.py", line 364, in <lambda>
    func = lambda x, y: x.replace(y[0], y[1])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128)
```

More meza breakages :-)
At this point I gave up.

https://github.com/djmuhlestein/csv2ofx has a UBS mapping which actually works, I think, for my needs.

**Comment by alper** [comment]
I hot-patched mine to pass in the delimiter but this should not be a hard fix. Let me see if I can find the time to fix this.

In `main.py`:
`records = read_csv(source, has_header=cont.has_header, delimiter=';')`

**Comment by reubano** [comment]
As @alper pointed out, the fix should be in [main.py](https://github.com/reubano/csv2ofx/blob/master/csv2ofx/main.py#L148). The `cont` object should have a `delimiter` property that defaults to `,`.

**Comment by sphakka** [comment]
Updated but still can't get my mapping + example to work as per my first post. Output is (Python-3.4.6 in a venv):

```
after_comma: None
after_decimal: None
usage: csv2ofx [options] <source> <dest>

description: csv2ofx converts a csv file to ofx and qif
...
``` 
The full help follows the ellipsis. Moreover, the exit code looks wrong:
```
$ echo $?
0
```

**Comment by reubano** [comment]
What command did you enter?

**Comment by sphakka** [comment]
`$ csv2ofx -m ubs-test UBS-CH_export_test.csv`

Where `ubs-test` and `UBS-CH_export_test.csv` are as in my first comment above.

**Comment by sphakka** [comment]
I finally managed to have a good mapping for my case. The issue was masked by the fact that `main.py` doesn't handle well `ValueError` exceptions triggered during transaction parsing at deeper level, f.i., when the transaction has keys with empty value as in CVS exports with separate debit/credit columns. 

 Moreover, it looks like `sys.exit` is recommended with Python 3 -- or at least `ipdb` didn't like it... 

So a minimal patch might be:
```
--- main.py.orig	2018-02-20 21:18:02.751228108 +0100
+++ main.py.new	2018-02-22 18:47:14.111686097 +0100
@@ -24,7 +24,7 @@
 import itertools as it
 import traceback
 
-from sys import stdin, stdout
+from sys import stdin, stdout, exit
 from importlib import import_module
 from imp import find_module, load_module
 from pkgutil import iter_modules
@@ -190,9 +190,9 @@
             msg += 'Check `start` and `end` options.'
         else:
             msg += 'Try again with `-c` option.'
-    except ValueError:
-        # csv2ofx called with no arguments
-        msg = 0
+    except ValueError as err:
+        # csv2ofx called with no arguments or broken mapping
+        msg = 'Possible mapping problem: %s. ' % str(err);
         parser.print_help()
     except Exception as err:  # pylint: disable=broad-except
         msg = 1
```
Here is the working mapping (feel free to add it to the repo):
```
# -*- coding: utf-8 -*-
"""
mapping for UBS Switzerland (French)

"""
__author__ = 'Marco "sphakka" Poleggi'

from operator import itemgetter

mapping = {
    'delimiter' : ';',
    'bank'      : 'UBS Switzerland',
    'has_header': True,
    'currency'  : itemgetter('Monn.'),
    'account'   : itemgetter('Produit'),
    # 'Débit' and 'Crédit' columns are always provided, but only one may have a value in a given row
    'type'      : lambda tr: 'debit' if tr.get('Débit') != '' else 'credit',
    'amount'    : lambda tr: tr['Débit'] or tr['Crédit'],
    'class'     : itemgetter('Description 1'),
    'notes'     : itemgetter('Description 2'),
    'date'      : itemgetter('Date de valeur'),
    'desc'      : itemgetter('Description 3'),
    'payee'     : itemgetter('Description 2'),
    'check_num' : itemgetter('N° de transaction'),
    'balance'   : itemgetter('Solde'),
}
```
I guess the 'type' and 'amount' keys should be modified accordingly in the already shipped `ubs.py` mapping.

**Comment by reubano** [comment]
Great work! Would you mind submitting 2 PRs with these updates?
